cards/Classes/Hunter/Spells/3 Cost/masters_call.js
src/functions.js
src/interact.js

Fixed Master's Call

---

cards/Classes/Hunter/Spells/3 Cost/masters_call.js
cards/Classes/Neutral/Minions/1 Cost/toxfin.js
cards/Classes/Neutral/Minions/3 Cost/nerubian_vizier.js
cards/Classes/Neutral/Minions/8 Cost/invincible.js
cards/Classes/Neutral/Minions/9 Cost/dragonqueen_alexstrasza.js
cards/Classes/Neutral/Minions/9 Cost/flesh_behemoth.js
cards/Classes/Neutral/Minions/9 Cost/nzoth_god_of_the_deep.js
cards/Classes/Paladin/Minions/2 Cost/redscale_dragontamer.js
cards/Classes/Paladin/Minions/4 Cost/goldwing.js
cards/Classes/Paladin/Minions/5 Cost/the_purator.js
cards/Classes/Paladin/Minions/8 Cost/murgur_murgurgle_prime.js
cards/Classes/Shaman/Minions/2 Cost/firemancer_flurgl.js
cards/Classes/Shaman/Quests/Command The Elements/stormcaller_brukan.js
cards/Classes/Shaman/Spells/2 Cost/ice_fishing.js
src/functions.js

Made `this has all minion types` work

---

src/game.js
test.js

This will help discover crashes and infinite loops in the program.

Added test script

---

deck_creator/index.js
src/interact.js

Made the deck creator view command better #13

---

config/ai.json
src/ai.js
src/interact.js

Allowed user to switch between ai attack models

---

cards/Classes/Druid/Minions/4 Cost/floop.js
cards/Classes/Warrior/Minions/9 Cost/rattlegore.js
src/card.js
src/interact.js

Improved backups

---

config/general.json
src/ai.js
src/card.js
src/functions.js
src/game.js
src/interact.js

Added missing docstrings

---

card_creator/generator/package.json
card_creator/package.json
deck_creator/package.json
package.json
src/index.js
src/interact.js

Updated old name in code

---

cards/Classes/Warlock/Spells/1 Cost/grimoire_of_sacrifice.js
src/game.js
src/interact.js
test-output.txt
test.js

Made tester handle crashes

---

deck_creator/index.js

Fixed a bug in the deck creator.

---

src/interact.js

Unified viewing cards

---

breaking_change/index.js
cards/Classes/Death Knight/Minions/2 Cost/hematurge.js
cards/Classes/Hunter/Secrets/wandering_monster.js
cards/Classes/Mage/Minions/2 Cost/prismatic_elemental.js
cards/Classes/Neutral/Minions/2 Cost/zephrys_the_great.js
cards/Classes/Neutral/Minions/3 Cost/nerubian_vizier.js
cards/Classes/Neutral/Minions/4 Cost/school_teacher.js
cards/Classes/Neutral/Minions/6 Cost/arcane_dynamo.js
cards/Classes/Neutral/Minions/9 Cost/dragonqueen_alexstrasza.js
cards/Classes/Neutral/Spells/9 Cost/the_sunwell.js
cards/Classes/Paladin/Minions/8 Cost/murgur_murgurgle_prime.js
cards/Classes/Paladin/Spells/2 Cost/legendary_invitation.js
cards/Classes/Priest/Spells/3 Cost/palm_reading.js
cards/Classes/Rogue/Minions/1 Cost/swashburglar.js
cards/Classes/Rogue/Spells/2 Cost/clever_disguise.js
cards/Classes/Rogue/Spells/2 Cost/jackpot.js
cards/Classes/Rogue/Spells/3 Cost/tooth_of_nafarian.js
cards/Classes/Rogue/Spells/4 Cost/academic_espionage.js
cards/Classes/Shaman/Heroes/8 Cost/hagatha_the_witch.js
cards/Classes/Shaman/Spells/2 Cost/devolve.js
cards/Classes/Warrior/Minions/8 Cost/rotface.js
src/card.js
src/functions.js
src/game.js
src/index.js
src/interact.js

Made getCards return a list

---

src/card.js

Added `perfectCopy` and `imperfectCopy` to cards

---

config/ai.json
src/ai.js
src/game.js

Made the ai trade better

---

cards/Classes/Death Knight/Weapons/7 Cost/the_lich_king's_frostmourne.js
cards/Classes/Druid/Minions/3 Cost/oracle_of_elune.js
cards/Classes/Neutral/Minions/3 Cost/acolyte_of_pain.js
cards/Classes/Neutral/Minions/3 Cost/augmented_elekk.js
cards/Classes/Neutral/Minions/3 Cost/brann_bronzebeard.js
cards/Classes/Neutral/Minions/4 Cost/spiritsinger_umbra.js
cards/Classes/Neutral/Minions/6 Cost/gadgetzan_auctioneer.js
cards/Classes/Neutral/Minions/8 Cost/kel'thuzad.js
cards/Classes/Priest/Minions/1 Cost/northshire_cleric.js
cards/Classes/Warrior/Minions/8 Cost/rotface.js
src/ai.js
src/card.js
src/functions.js
src/game.js
src/interact.js

Resolved todo's

---

config/general.json
index.js
package-lock.json
package.json
src/interact.js

Bump version to 1.2

---

cards/Classes/Druid/Minions/5 Cost/elise_the_enlightened.js
cards/Classes/Neutral/Minions/2 Cost/zephrys_the_great.js
cards/Classes/Neutral/Minions/6 Cost/reno_jackson.js
cards/Classes/Neutral/Minions/9 Cost/dragonqueen_alexstrasza.js
cards/Classes/Priest/Minions/3 Cost/handmaiden.js
cards/Classes/Priest/Minions/5 Cost/raza_the_chained.js
cards/Tests/condition.js
cards/Tests/condition2.js
config/general.json
events.txt
src/card.js
src/game.js
src/interact.js

Added condition system

---

src/interact.js

Made mulligan show more information

---

.gitignore
src/game.js

Fixed infuse bug

---

src/game.js

Fixed a bug when applying enchantments to minions

---

cards/Classes/Warlock/Spells/3 Cost/fel_rift.js
cards/Tests/cast_on_draw.js
src/player.js

Replaced `castondraw` with a keyword

---

src/interact.js

Made the debug deck only work in debug mode

---

cards/Classes/Death Knight/Minions/2 Cost/hematurge.js
cards/Classes/Druid/Spells/2 Cost/moonlit_guidance.js
cards/Classes/Hunter/Spells/1 Cost/tracking.js
cards/Classes/Hunter/Spells/3 Cost/masters_call.js
cards/Classes/Mage/Minions/2 Cost/prismatic_elemental.js
cards/Classes/Neutral/Minions/2 Cost/zephrys_the_great.js
cards/Classes/Neutral/Minions/4 Cost/school_teacher.js
cards/Classes/Neutral/Minions/6 Cost/arcane_dynamo.js
cards/Classes/Neutral/Minions/6 Cost/duke_theotar.js
cards/Classes/Priest/Spells/2 Cost/shadow_visions.js
cards/Classes/Priest/Spells/2 Cost/thrive_in_the_shadows.js
cards/Classes/Priest/Spells/3 Cost/identity_theft.js
cards/Classes/Priest/Spells/3 Cost/palm_reading.js
cards/Classes/Rogue/Spells/3 Cost/tooth_of_nafarian.js
cards/Classes/Warlock/Spells/4 Cost/tamsins_phylactery.js
cards/Lackeys/ethereal.js
src/interact.js

Removed redundant arguments from discover

---

cards/Debug/10mana.js
cards/Debug/infmana.js

Created debug cards folder

---

cards/Tests/placeholder.js
src/card.js
src/game.js
src/interact.js

Added placeholder system

---

cards/Tests/placeholder.js
src/interact.js

Fixed double-digit placeholder ids

---

.github/ISSUE_TEMPLATE/bug_report.md
.gitignore
src/functions.js
src/index.js
src/interact.js
test.js

Fixed #105
- Made a crash report system
- Updated the bug report templatr

Made a crash report system

---

card_creator/vanilla/index.js
package-lock.json
package.json
src/functions.js
src/interact.js

Support for vanilla deckcodes

---

cards/Tests/finale.js
src/game.js

Added the finale keyword

---

cards/Tests/overheal.js
src/card.js

Fixed #116
- Added overheal keyword
- Added overheal test card

Added overheal keyword

---

deck_creator/index.js
src/functions.js
src/index.js
src/interact.js
test.js

Moved all deckcode functions into another class

---

deck_creator/index.js
src/ai.js
src/card.js
src/functions.js
src/index.js
src/player.js
src/shared.js
test.js
test/functions.test.js

Made sharing the game constant better

---

test/functions.test.js

Added missing quest tests

---

src/ai.js
src/card.js

Prevent ai from attacking stealthed targets

---

deck_creator/index.js

Removed `forcevanilla`

---

src/interact.js

Removed `curr` from the interact module

---

src/card.js
src/interact.js

Prevented location cards from being damaged indirectly

---

card_creator/index.js
card_creator/vanilla/index.js
index.js
src/functions.js

Made the card creator add some comments to cards

---

src/functions.js
test/functions.test.js

Improved parseTags

---

scripts/card_updater/index.js

Filter card updater cards

---

src/game.js
src/interact.js

Added argument validation to some game functions

---

cards/Classes/Demon Hunter/Spells/5 Cost/topple_the_idol.js
cards/Classes/Neutral/Minions/1 Cost/elwynn_boar.js
config/general.json
package-lock.json
package.json
src/interact.js

Stabilize & Bump version to 1.5

---

config/general.json
src/interact.js

Removed the history warning

---

card_creator/index.js
card_creator/vanilla/index.js

Look up vanilla cards using their dbfid

---

card_creator/class/index.js
card_creator/index.js
card_creator/vanilla/generator.js
card_creator/vanilla/index.js
cards/Classes/Neutral/Minions/1 Cost/sir_finley_mrrgglton.js
deck_creator/index.js
run-tests.js
scripts/breaking_change/index.js
scripts/card_updater/index.js
scripts/crashtest.js
src/functions.js
src/index.js
test/ai.test.js
test/card.test.js
test/functions.test.js
test/game.test.js
test/interact.test.js
test/player.test.js

Remove game.dirname

---

.github/ISSUE_TEMPLATE/bug_report.md
src/functions.js
src/interact.js

Merge the two log files

---

package.json
src/functions.js
src/index.js
src/interact.js

Update old name in package.json

---

cards/Classes/Druid/Spells/2 Cost/moonlit_guidance.js
cards/Classes/Hunter/Spells/1 Cost/tracking.js
cards/Classes/Hunter/Spells/3 Cost/masters_call.js
cards/Classes/Mage/Minions/2 Cost/prismatic_elemental.js
cards/Classes/Neutral/Minions/2 Cost/zephrys_the_great.js
cards/Classes/Neutral/Minions/6 Cost/duke_theotar.js
cards/Classes/Paladin/Spells/2 Cost/legendary_invitation.js
cards/Classes/Priest/Spells/2 Cost/shadow_visions.js
cards/Classes/Priest/Spells/2 Cost/thrive_in_the_shadows.js
cards/Classes/Priest/Spells/3 Cost/identity_theft.js
cards/Classes/Rogue/Spells/3 Cost/tooth_of_nafarian.js
cards/Classes/Warlock/Spells/4 Cost/tamsins_phylactery.js
cards/Examples/3/discover.js
src/interact.js

Discover filter class cards by default

---

src/game.js

Remove this

---

card_creator/class/index.js

Fix class creator bug

---

cards/Classes/Druid/Minions/3 Cost/oracle_of_elune.js
cards/Classes/Druid/Minions/4 Cost/floop.js
cards/Classes/Hunter/Secrets/freezing_trap.js
cards/Classes/Neutral/Minions/3 Cost/augmented_elekk.js
cards/Classes/Neutral/Minions/5 Cost/faceless_manipulator.js
cards/Classes/Priest/Minions/1 Cost/voidtouched_attendant.js
cards/Classes/Priest/Minions/3 Cost/mindrender_illucia.js
src/card.js
src/functions.js
src/game.js
src/interact.js
src/player.js
test/card.test.js

Remove update parameter from all functions

---

src/interact.js

History show revealed cards

---

cards/Tests/placeholer_card.js
config/advanced.json
package-lock.json
package.json
src/card.js
src/functions.js
src/index.js
src/interact.js
src/player.js
test/card.test.js
test/functions.test.js

Closes #236 
Reworked the placeholder system
Changed detail mode to be a toggle

Added card placeholder

---

cards/Examples/3/1_manathirst.js
cards/Examples/3/2_discover.js
src/card.js
src/game.js
src/interact.js
src/player.js
src/types.js

Add constants for constant values

---

src/interact.js

Closes #250 
Added the `cmd` debug command

Add a command history

---

cards/Classes/Neutral/Minions/3 Cost/prince_renathal.js
deck_creator/index.js
src/functions.js
src/game.js
test/ai.test.js

Make `Prince Renathal` not as hardcoded

---

cards/Examples/1/6_dredge.ts
cards/HeroPower/Shaman/Basic/strength_totem.ts
cards/Lackeys/faceless.ts
cards/Lackeys/witchy.ts
cards/StartingHeroes/shaman.ts
package-lock.json
package.json
scripts/crashtest.ts
src/core/card.ts
src/core/functions.ts
src/core/game.ts
src/core/interact.ts
src/core/player.ts
src/types.ts
tools/cardcreator/vanilla.ts
tools/deckcreator.ts

Add lodash

---

src/core/functions/util.ts
src/index.ts

fix: prevent eval commands in replay files
